CREATE DATABASE IF NOT EXISTS sharehubs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sharehubs;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  token VARCHAR(64) DEFAULT NULL,
  token_expires DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_token (token), INDEX idx_email (email)
) ENGINE=InnoDB;
